### ISSUE TITLE
Small Nits

### ISSUE THREAD

**Issue by moonshiner** [peterthomassen/draft-ietf-dnsop-cds-consistency#1]
From the nits tool

  ** The document seems to lack an IANA Considerations section.  (See Section
     2.2 of https://www.ietf.org/id-info/checklist for how to handle the case
     when there are no actions for IANA.)

  ** The abstract seems to contain references ([RFC7344], [RFC7477]), which
     it shouldn't.  Please replace those with straight textual mentions of the
     documents in question.

  -- The draft header indicates that this document updates RFC7344, but the
     abstract doesn't seem to directly say this.  It does mention RFC7344
     though, so this could be OK.

  -- The draft header indicates that this document updates RFC7477, but the
     abstract doesn't seem to directly say this.  It does mention RFC7477
     though, so this could be OK.

(the last two are because of the refs being ignored in the abstract)

https://author-tools.ietf.org/api/idnits?url=https://www.ietf.org/archive/id/draft-thomassen-dnsop-cds-consistency-03.txt

**Comment by peterthomassen** [comment]
thanks!
